### PR TITLE
Use strip to avoid nil result

### PR DESCRIPTION
**Pull request by dlackty**
According to [Ruby's API doc](https://ruby-doc.org/core-2.3.1/String.html#method-i-strip-21) of `strip!`:

> Removes leading and trailing whitespace from str. Returns nil if str was not altered.

### CODE REVIEW

**Comment by abookyun** [comment]
@dlackty Notice: TravisCI has failed. :[

**Comment by dlackty** [comment]
Rails 5 no longer supports older Ruby versions. A simple way to fix this is just removing legacy Ruby versions from CI build matrix. 

What do you think?

**Comment by abookyun** [comment]
Yes, please do it.

**Comment by dlackty** [comment]
Fixed. Please have a look.

**Comment by abookyun** [comment]
OK, thanks. Let's merge in! :shipit:

**Comment by abookyun** [comment]
Bumped and released to RubyGems. Thanks.

**Pull request merged**
